language: node_js

env:
  - DATABASE_URL=postgresql://postgresql@localhost:5432/greeting

node_js:  
  - "12.18.3"

before_script:
  - psql -c 'create database  greeting;' -U postgres
  - psql -U postgres -d greeting -a -f database.sql

services:
  - postgresql